### ISSUE TITLE
Bugs in formula

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/opensds-formula#1]
Number of issues to be addressed - various formulae.  

Also some states  not running in expected order (i.e. Devstack).

```
Summary for local
--------------
Succeeded: 116 (changed=54)
Failed:     22
--------------
Total states run:     138
Total run time:   309.985 s
```
**golang** intermittent problem?
```
[ERROR   ] Alternative for link-godoc not installed: 
[ERROR   ] Alternative for link-gofmt not installed: 
[ERROR   ] Alternative for link-go not installed: 
```

**docker** formula is not detecting `docker.container.skip_translate: ports`  ???
```
[ERROR   ] Failed to translate input. Additional info follows:
invalid:
    ----------
    ports:
        '{u'50050/tcp': OrderedDict([(u'HostPort', u'50050'), (u'HostIp', u'192.168.1.1')])}' is not a valid port definition
If you feel this information is incorrect, the skip_translate argument can be used to skip input translation for the argument(s) identified as invalid. See the documentation for details.
[ERROR   ] Failed to translate input. Additional info follows:
.. etc ...
```

**file.line** this always gives troubles.
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1831, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 3933, in line
    backup=backup, quiet=quiet, indent=indent)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 2017, in line
    raise CommandExecutionError("Wrong conditions? "
CommandExecutionError: Wrong conditions? Unable to ensure line without knowing where to put it before and/or after.
```
**devstack**  ... Where is string "Service" coming from?  Bad Pillars?
```
 [ERROR   ] stderr: usage: openstack service create [-h] [-f {json,shell,table,value,yaml}]
                                [-c COLUMN] [--max-width <integer>]
                                [--fit-width] [--print-empty] [--noindent]
                                [--prefix PREFIX] [--name <name>]
                                [--description <description>]
                                [--enable | --disable]
                                <type>
openstack service create: error: unrecognized arguments: --type Service opensdsv0.3.0
```
**opensds/files/macros.jinja** minor bug
```
          ID: opensds dock block generate lvm driver file
    Function: file.managed
        Name: /etc/opensds/driver/lvm.yaml
      Result: False
     Comment: Unable to manage file: Jinja variable 'spaces' is undefined
     Started: 22:52:38.763556
    Duration: 30.78 ms
     Changes:   
```
**lvm** why did lvm.files.create state not run?
```
          ID: lvm_pv_create_/dev/loop0
    Function: lvm.pv_present
        Name: /dev/loop0
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1831, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/lvm.py", line 66, in pv_present
                  changes = __salt__['lvm.pvcreate'](name, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/linux_lvm.py", line 228, in pvcreate
                  raise CommandExecutionError('{0} does not exist'.format(device))
              CommandExecutionError: /dev/loop0 does not exist
     Started: 22:52:36.938774
    Duration: 377.737 ms
     Changes:  
```

**etcd formula**   Check RedHat...
```
 ID: etcd-docker-python-docker-py-package
    Function: pkg.installed
        Name: python-docker-py
      Result: False
     Comment: The following packages failed to install/update: python-docker-py
     Started: 22:52:04.979023
    Duration: 2930.643 ms
     Changes:   
```

**k8s**   Business logic issue with opensds installer
```
          ID: opensds nbp plugins k8s start
    Function: cmd.run
        Name: source /etc/profile && kubectl create -f deploy/kubernetes
      Result: False
     Comment: Command "source /etc/profile && kubectl create -f deploy/kubernetes" run
     Started: 22:52:04.895546
    Duration: 26.312 ms
     Changes:   
              ----------
              pid:
                  22219
              retcode:
                  127
              stderr:
                  /bin/bash: kubectl: command not found
              stdout:
```

**Comment by noelmcloughlin** [comment]
Still some outstanding issues.

**Comment by aboe76** [comment]
merged all saltstack issues
